# Generated by Django 5.2.5 on 2025-09-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNotification', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
