# Generated by Django 5.2.5 on 2025-09-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNotification', '0003_response_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='notify_subscribers',
            field=models.BooleanField(default=True, verbose_name='Notify subscribers'),
        ),
    ]
