# Generated by Django 5.2.5 on 2025-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNotification', '0004_news_notify_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notify_subscribers',
            field=models.BooleanField(default=True, verbose_name='Notify subscribers'),
        ),
    ]
