# Generated by Django 5.2.5 on 2025-09-04 16:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNotification', '0005_post_notify_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='You can use rich text editor with images, videos and formatting', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for the post card', null=True, upload_to='posts/images/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Main video file (optional)', null=True, upload_to='posts/videos/', verbose_name='Main Video'),
        ),
    ]
